package com.cpxiao.free1010plus.utils;

/**
 * Created by cpxiao on 3/5/16.
 * Extra
 */
public interface Extra {
    String INTENT_EXTRA_GAME_TYPE = "INTENT_EXTRA_GAME_TYPE";
    String INTENT_EXTRA_DIFFICULTY = "INTENT_EXTRA_DIFFICULTY";
    String INTENT_EXTRA_IS_NEW_GAME = "INTENT_EXTRA_IS_NEW_GAME";


    String KEY_CONTINUE_BLOCKS = "KEY_CONTINUE_BLOCKS";
    String KEY_CONTINUE_BLOCKS_BASE = "KEY_CONTINUE_BLOCKS_BASE";
    String KEY_CONTINUE_SCORE = "KEY_CONTINUE_SCORE";


}
